#!/bin/bash
#++++++++++++++++++++++++++ Script begins here ++++++++++++++++++++++++++
if [ "$1" == "-h" ] || [ "$1" == "-help" ] || [ "$1" == "--help" ]; then
	########## HELP begins here ##########
	echo
	echo "Zero-pad enumeration"
	echo " e.g. [0002 0003 0004] \$ `basename $0` 2 4 4"
	echo " \$ `basename $0` <start> <end> <digits>"
	echo
	########### HELP ends here ###########
else
	if [ -z $1 ]; then
		$0 --help
	else
		########## BODY begins here ##########
		if [ "$1" == "$2" ]; then
			for ((i=$1; i<=$2; i+=1)); do printf "%0"$3"d" " $i"; done; echo
		else
			for ((i=$1; i<=$2; i+=1)); do printf "%0"$3"d" " $i"; echo -ne " "; done; echo
		fi
		########### BODY ends here ###########
	fi
fi
#+++++++++++++++++++++++++++ Script ends here +++++++++++++++++++++++++++
